name: Python app with Whisper API and ffmpeg

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Python 설정
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # 3. 프로젝트 의존성 설치
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. ffmpeg 설치
    - name: Install ffmpeg
      run: sudo apt-get install -y ffmpeg

    # 5. ffmpeg 경로 확인
    - name: Check ffmpeg path
      run: which ffmpeg
